# Əsas Node.js imicini seçirik
FROM node:20-slim

# Serverin paket siyahısını yeniləyir və lazım olan paketləri quraşdırırıq (ffmpeg və yt-dlp)
# Bütün apt əməliyyatları vahid bir layerdə icra olunur ki, konteyner ölçüsü kiçik qalsın.
RUN apt-get update -y && \
    apt-get install -y ffmpeg yt-dlp && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Tətbiqin yerləşəcəyi qovluq
WORKDIR /app

# 1. Asılılıqları quraşdırmaq üçün package.json fayllarını kopyalayırıq
COPY package*.json ./

# 2. Node.js asılılıqlarını quraşdırırıq (ƏSAS FƏRQ BURDADIR)
RUN npm install

# 3. Qalan bütün faylları (index.js daxil) kopyalayırıq
COPY . .

# Botumuzun dinləyəcəyi port
EXPOSE 8080

# Botu işə salmaq üçün əmrdir
CMD [ "npm", "start" ]